//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EquimarFac.FelWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConexionRemota32Soap", Namespace="https://www.fel.mx/ConexionRemotaCFDI")]
    public partial class ConexionRemota32 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerarCFDIv32OperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarCodigoBidimensionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarCFDIOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarCFDIOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerNumeroCreditosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConexionRemota32() {
            this.Url = global::EquimarFac.Properties.Settings.Default.EquimarFac_FelWebService_ConexionRemota32;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerarCFDIv32CompletedEventHandler GenerarCFDIv32Completed;
        
        /// <remarks/>
        public event GenerarCodigoBidimensionalCompletedEventHandler GenerarCodigoBidimensionalCompleted;
        
        /// <remarks/>
        public event CancelarCFDICompletedEventHandler CancelarCFDICompleted;
        
        /// <remarks/>
        public event EnviarCFDICompletedEventHandler EnviarCFDICompleted;
        
        /// <remarks/>
        public event ObtenerPDFCompletedEventHandler ObtenerPDFCompleted;
        
        /// <remarks/>
        public event ObtenerNumeroCreditosCompletedEventHandler ObtenerNumeroCreditosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.fel.mx/ConexionRemotaCFDI/GenerarCFDIv32", RequestNamespace="https://www.fel.mx/ConexionRemotaCFDI", ResponseNamespace="https://www.fel.mx/ConexionRemotaCFDI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GenerarCFDIv32(string[] datosUsuario, string[] datosReceptor, string[] datosCFDI, string[] etiquetas, string[] conceptos, string[] informacionAduanera, string[] retenciones, string[] traslados, string[] retencionesLocales, string[] trasladosLocales) {
            object[] results = this.Invoke("GenerarCFDIv32", new object[] {
                        datosUsuario,
                        datosReceptor,
                        datosCFDI,
                        etiquetas,
                        conceptos,
                        informacionAduanera,
                        retenciones,
                        traslados,
                        retencionesLocales,
                        trasladosLocales});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GenerarCFDIv32Async(string[] datosUsuario, string[] datosReceptor, string[] datosCFDI, string[] etiquetas, string[] conceptos, string[] informacionAduanera, string[] retenciones, string[] traslados, string[] retencionesLocales, string[] trasladosLocales) {
            this.GenerarCFDIv32Async(datosUsuario, datosReceptor, datosCFDI, etiquetas, conceptos, informacionAduanera, retenciones, traslados, retencionesLocales, trasladosLocales, null);
        }
        
        /// <remarks/>
        public void GenerarCFDIv32Async(string[] datosUsuario, string[] datosReceptor, string[] datosCFDI, string[] etiquetas, string[] conceptos, string[] informacionAduanera, string[] retenciones, string[] traslados, string[] retencionesLocales, string[] trasladosLocales, object userState) {
            if ((this.GenerarCFDIv32OperationCompleted == null)) {
                this.GenerarCFDIv32OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarCFDIv32OperationCompleted);
            }
            this.InvokeAsync("GenerarCFDIv32", new object[] {
                        datosUsuario,
                        datosReceptor,
                        datosCFDI,
                        etiquetas,
                        conceptos,
                        informacionAduanera,
                        retenciones,
                        traslados,
                        retencionesLocales,
                        trasladosLocales}, this.GenerarCFDIv32OperationCompleted, userState);
        }
        
        private void OnGenerarCFDIv32OperationCompleted(object arg) {
            if ((this.GenerarCFDIv32Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarCFDIv32Completed(this, new GenerarCFDIv32CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.fel.mx/ConexionRemotaCFDI/GenerarCodigoBidimensional", RequestNamespace="https://www.fel.mx/ConexionRemotaCFDI", ResponseNamespace="https://www.fel.mx/ConexionRemotaCFDI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GenerarCodigoBidimensional(string[] datosUsuario, string UUID) {
            object[] results = this.Invoke("GenerarCodigoBidimensional", new object[] {
                        datosUsuario,
                        UUID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GenerarCodigoBidimensionalAsync(string[] datosUsuario, string UUID) {
            this.GenerarCodigoBidimensionalAsync(datosUsuario, UUID, null);
        }
        
        /// <remarks/>
        public void GenerarCodigoBidimensionalAsync(string[] datosUsuario, string UUID, object userState) {
            if ((this.GenerarCodigoBidimensionalOperationCompleted == null)) {
                this.GenerarCodigoBidimensionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarCodigoBidimensionalOperationCompleted);
            }
            this.InvokeAsync("GenerarCodigoBidimensional", new object[] {
                        datosUsuario,
                        UUID}, this.GenerarCodigoBidimensionalOperationCompleted, userState);
        }
        
        private void OnGenerarCodigoBidimensionalOperationCompleted(object arg) {
            if ((this.GenerarCodigoBidimensionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarCodigoBidimensionalCompleted(this, new GenerarCodigoBidimensionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.fel.mx/ConexionRemotaCFDI/CancelarCFDI", RequestNamespace="https://www.fel.mx/ConexionRemotaCFDI", ResponseNamespace="https://www.fel.mx/ConexionRemotaCFDI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CancelarCFDI(string[] datosUsuario, string[] ListaACancelar) {
            object[] results = this.Invoke("CancelarCFDI", new object[] {
                        datosUsuario,
                        ListaACancelar});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CancelarCFDIAsync(string[] datosUsuario, string[] ListaACancelar) {
            this.CancelarCFDIAsync(datosUsuario, ListaACancelar, null);
        }
        
        /// <remarks/>
        public void CancelarCFDIAsync(string[] datosUsuario, string[] ListaACancelar, object userState) {
            if ((this.CancelarCFDIOperationCompleted == null)) {
                this.CancelarCFDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarCFDIOperationCompleted);
            }
            this.InvokeAsync("CancelarCFDI", new object[] {
                        datosUsuario,
                        ListaACancelar}, this.CancelarCFDIOperationCompleted, userState);
        }
        
        private void OnCancelarCFDIOperationCompleted(object arg) {
            if ((this.CancelarCFDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarCFDICompleted(this, new CancelarCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.fel.mx/ConexionRemotaCFDI/EnviarCFDI", RequestNamespace="https://www.fel.mx/ConexionRemotaCFDI", ResponseNamespace="https://www.fel.mx/ConexionRemotaCFDI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EnviarCFDI(string[] datosUsuario, string UUID, string email) {
            object[] results = this.Invoke("EnviarCFDI", new object[] {
                        datosUsuario,
                        UUID,
                        email});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EnviarCFDIAsync(string[] datosUsuario, string UUID, string email) {
            this.EnviarCFDIAsync(datosUsuario, UUID, email, null);
        }
        
        /// <remarks/>
        public void EnviarCFDIAsync(string[] datosUsuario, string UUID, string email, object userState) {
            if ((this.EnviarCFDIOperationCompleted == null)) {
                this.EnviarCFDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarCFDIOperationCompleted);
            }
            this.InvokeAsync("EnviarCFDI", new object[] {
                        datosUsuario,
                        UUID,
                        email}, this.EnviarCFDIOperationCompleted, userState);
        }
        
        private void OnEnviarCFDIOperationCompleted(object arg) {
            if ((this.EnviarCFDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarCFDICompleted(this, new EnviarCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.fel.mx/ConexionRemotaCFDI/ObtenerPDF", RequestNamespace="https://www.fel.mx/ConexionRemotaCFDI", ResponseNamespace="https://www.fel.mx/ConexionRemotaCFDI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerPDF(string[] datosUsuario, string UUID) {
            object[] results = this.Invoke("ObtenerPDF", new object[] {
                        datosUsuario,
                        UUID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPDFAsync(string[] datosUsuario, string UUID) {
            this.ObtenerPDFAsync(datosUsuario, UUID, null);
        }
        
        /// <remarks/>
        public void ObtenerPDFAsync(string[] datosUsuario, string UUID, object userState) {
            if ((this.ObtenerPDFOperationCompleted == null)) {
                this.ObtenerPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPDFOperationCompleted);
            }
            this.InvokeAsync("ObtenerPDF", new object[] {
                        datosUsuario,
                        UUID}, this.ObtenerPDFOperationCompleted, userState);
        }
        
        private void OnObtenerPDFOperationCompleted(object arg) {
            if ((this.ObtenerPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPDFCompleted(this, new ObtenerPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.fel.mx/ConexionRemotaCFDI/ObtenerNumeroCreditos", RequestNamespace="https://www.fel.mx/ConexionRemotaCFDI", ResponseNamespace="https://www.fel.mx/ConexionRemotaCFDI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerNumeroCreditos(string[] datosUsuario) {
            object[] results = this.Invoke("ObtenerNumeroCreditos", new object[] {
                        datosUsuario});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerNumeroCreditosAsync(string[] datosUsuario) {
            this.ObtenerNumeroCreditosAsync(datosUsuario, null);
        }
        
        /// <remarks/>
        public void ObtenerNumeroCreditosAsync(string[] datosUsuario, object userState) {
            if ((this.ObtenerNumeroCreditosOperationCompleted == null)) {
                this.ObtenerNumeroCreditosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerNumeroCreditosOperationCompleted);
            }
            this.InvokeAsync("ObtenerNumeroCreditos", new object[] {
                        datosUsuario}, this.ObtenerNumeroCreditosOperationCompleted, userState);
        }
        
        private void OnObtenerNumeroCreditosOperationCompleted(object arg) {
            if ((this.ObtenerNumeroCreditosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerNumeroCreditosCompleted(this, new ObtenerNumeroCreditosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GenerarCFDIv32CompletedEventHandler(object sender, GenerarCFDIv32CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarCFDIv32CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarCFDIv32CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GenerarCodigoBidimensionalCompletedEventHandler(object sender, GenerarCodigoBidimensionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarCodigoBidimensionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarCodigoBidimensionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CancelarCFDICompletedEventHandler(object sender, CancelarCFDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelarCFDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelarCFDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void EnviarCFDICompletedEventHandler(object sender, EnviarCFDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarCFDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarCFDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ObtenerPDFCompletedEventHandler(object sender, ObtenerPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ObtenerNumeroCreditosCompletedEventHandler(object sender, ObtenerNumeroCreditosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerNumeroCreditosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerNumeroCreditosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591